name: Bot Minecraft 24h

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install mineflayer mineflayer-pathfinder
      - name: Rodar o Bot
        run: node bot.js
